# Generated by Django 5.1.7 on 2025-05-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_user_image_alter_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
