# Generated by Django 5.1.7 on 2025-05-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/Y%/%m'),
        ),
    ]
